cmake_minimum_required(VERSION 3.16)

project(EX3 VERSION 1.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

add_executable(EX3 main.cpp)

FILE(GLOB TARGET_H "${CMAKE_SOURCE_DIR}/**/*.h")
FILE(GLOB TARGET_CPP "${CMAKE_SOURCE_DIR}/**/*.cpp")
SET(ALL_SOURCES ${TARGET_CPP} ${TARGET_H})

target_sources(EX3 PRIVATE ${ALL_SOURCES})

